services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: student-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Pass123"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  student-api:
    build:
      context: ./StudentManagement.Api
    container_name: studentapi-db

    # Note : this will inject automatically when we use docker else local connection string will be default
    environment:
      ConnectionStrings__DefaultConnection: "Server=student-sql;Database=StudentManagementDb;User Id=sa;Password=YourStrong@Pass123;TrustServerCertificate=True"

    ports:
      - "8080:8080"
    depends_on:
      - sqlserver

volumes:
  sql_data:
